### ISSUE TITLE
E(x.asg) is empty

### ISSUE THREAD

**Issue by corydeburd** [nypl-spacetime/map-vectorizer#29]
In using my own files, the area of different polygons can be quite variable. The intermediate output [file name].shp etc. looks great! However, the cleanup has some issues. Specifically, I get the error:

`Error in simple_es_index(x, ii) : Unknown edge selected
Calls: [ -> [.igraph.es -> lapply -> FUN -> simple_es_index
Execution halted`

I've traced the error to simplify_map.R's:
`cutg = x.asg - E(x.asg)[1]`
because E(x.asg) has 0 elements. 

The end result is that [file]-traced.shp is empty despite the code picking up many valid polygons in the first round. I'm still experimenting with the best alpha value to put here, but it seems like a quick fix here is to put in some code like this:

`				if (length(E(x.asg))==0) {
				  error = 3
				  # cat("Empty shape")
				}`

so that the R execution doesn't terminate upon hitting such a shape. Does this seem reasonable?

Files:
https://dl.dropboxusercontent.com/u/2135055/singida.tif
https://dl.dropboxusercontent.com/u/2135055/vectorize_config_default.txt
min area setting = 1 km^2 = (1000)^2 meters^2
max area setting = 125 km^2 = (125*1000)^2 meters^2
alpha = 1000

**Comment by mgiraldo** [comment]
i think that alpha value is too high. as you can see in [this example that simplifies norway](http://rpubs.com/geospacedman/alphasimple), and which i based part of the vectorizer on, their value is 2. i think the max value is around there (you can also check [the math behind alphahull](https://cran.r-project.org/web/packages/alphahull/vignettes/alphahull.pdf)). i've been wanting to make a scale-independent simplifier for a while: it would normalize all polygons and then do the simplification and then scale back to original size. one of the many tasks to do 🤷‍♂️.

i'd say you could [comment out lines 458-466](https://github.com/nypl-spacetime/map-vectorizer/blob/master/vectorize_map.py#L458-L466) in the python code (i've also wanted to add a command-line parameter so that one can decide if they want to clean up the folder or not) and then test the R code by itself with the intermediate files until you find the parameters that work for you. in theory, you should only need to change `alpha`, `numsample`, `minarea`, and `maxarea`. the rest of the code should be left alone (it was quite painful to check all those consistencies in the resulting shapes).

**Comment by corydeburd** [comment]
Thanks for this. For what it's worth, the issues cropped up no matter what set of values I picked (e.g. alpha = 2 as well). I ultimately decided just to rewrite the R code to remove the holes in the polygons but not to do any other smoothing -- this produces a pretty good result for my purposes.
